#!/usr/bin/env node
/**
 * generate-env.js
 * ───────────────
 * Bootstraps a ready-to-deploy .env file with auto-generated secrets.
 * Run once before your first deployment:
 *
 *   npm run setup
 *
 * What it does:
 *   • Auto-generates NEXTAUTH_SECRET, ADMIN_PASSWORD, WEBHOOK_SECRET
 *   • Fills in sensible defaults for everything else
 *   • Leaves obvious CHANGE_ME placeholders for things that need your input
 *     (Discord token, IMAP credentials, Mailcow URL/key, your domain)
 *   • Skips writing if .env already exists (pass --force to overwrite)
 *
 * No extra dependencies — uses Node.js built-ins only.
 */

"use strict";

const fs      = require("fs");
const path    = require("path");
const crypto  = require("crypto");
const readline = require("readline");

const ROOT    = path.resolve(__dirname, "..");
const OUT     = path.join(ROOT, ".env");
const EXAMPLE = path.join(ROOT, ".env.example");
const FORCE   = process.argv.includes("--force");

// ── Helpers ──────────────────────────────────────────────────────────────────

function randomBase64(bytes = 32) {
  return crypto.randomBytes(bytes).toString("base64");
}

function randomHex(bytes = 24) {
  return crypto.randomBytes(bytes).toString("hex");
}

/** Alphanumeric + symbols password (shell-safe: no $, `, \, ", ') */
function randomPassword(length = 20) {
  const charset = "ABCDEFGHIJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789!@#%^&*-_+=";
  let pw = "";
  const buf = crypto.randomBytes(length * 2);
  for (let i = 0; i < buf.length && pw.length < length; i++) {
    pw += charset[buf[i] % charset.length];
  }
  return pw;
}

function bold(s)  { return `\x1b[1m${s}\x1b[0m`; }
function green(s) { return `\x1b[32m${s}\x1b[0m`; }
function yellow(s){ return `\x1b[33m${s}\x1b[0m`; }
function cyan(s)  { return `\x1b[36m${s}\x1b[0m`; }
function red(s)   { return `\x1b[31m${s}\x1b[0m`; }

// ── Guard ────────────────────────────────────────────────────────────────────

if (fs.existsSync(OUT) && !FORCE) {
  console.log(yellow("⚠  .env already exists — skipping generation."));
  console.log(yellow("   Pass --force to overwrite:  npm run setup -- --force\n"));
  process.exit(0);
}

// ── Generate secrets ─────────────────────────────────────────────────────────

const NEXTAUTH_SECRET  = randomBase64(32);
const ADMIN_PASSWORD   = randomPassword(20);
const WEBHOOK_SECRET   = randomHex(24);

// ── Build .env content ───────────────────────────────────────────────────────

const env = `# ════════════════════════════════════════════════════════════════════
#  MailDrop — Environment Configuration
#  Generated by: npm run setup  (${new Date().toISOString()})
#
#  Lines marked with  ← CHANGE ME  MUST be edited before deploying.
#  Everything else has a sensible default or was auto-generated.
# ════════════════════════════════════════════════════════════════════

# ── NextAuth ─────────────────────────────────────────────────────────────────
# Auto-generated — do not share or commit this value.
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Full public URL of this deployment (no trailing slash).
# Local dev: http://localhost:3000
# Railway:   https://<your-service>.up.railway.app    ← CHANGE ME
NEXTAUTH_URL=http://localhost:3000

# ── Admin panel credentials ───────────────────────────────────────────────────
# Username is "admin" by default; change only if you need something else.
ADMIN_USERNAME=admin
# Auto-generated strong password — save this somewhere safe!
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# ── Mail domain ───────────────────────────────────────────────────────────────
# The domain used for generated inbox addresses, e.g.  user@mail.example.com
MAIL_DOMAIN=mail.example.com              # ← CHANGE ME

# ── Webhook secret ────────────────────────────────────────────────────────────
# Shared secret between your mail gateway and this app.
# Send it as the  X-Webhook-Secret  header when posting to /api/webhook/receive.
WEBHOOK_SECRET=${WEBHOOK_SECRET}

# ── Public website URL (used by the Discord bot in messages) ─────────────────
# Same as NEXTAUTH_URL in most cases.
WEBSITE_URL=http://localhost:3000         # ← CHANGE ME (your deployed URL)

# ── Discord bot ───────────────────────────────────────────────────────────────
# Get your token at https://discord.com/developers/applications
DISCORD_BOT_TOKEN=CHANGE_ME_discord_bot_token

# Command prefix.  Default: .   (e.g. .register, .balance)
DISCORD_BOT_PREFIX=.

# Comma-separated Discord user IDs that can use owner-only commands.
DISCORD_OWNER_IDS=CHANGE_ME_your_discord_user_id

# Channel ID where the bot posts automatic db.json backups every 6 hours.
# Leave the default (or set 0 to disable) if you don't need this.
BACKUP_CHANNEL_ID=0

# ── IMAP catch-all (polls your mail server for incoming messages) ─────────────
# Your Mailcow catch-all or any IMAP mailbox that receives all @MAIL_DOMAIN mail.
IMAP_HOST=mail.example.com               # ← CHANGE ME
IMAP_PORT=993
IMAP_SECURE=true
IMAP_USER=catchall@mail.example.com      # ← CHANGE ME
IMAP_PASS=CHANGE_ME_imap_password

# ── Mailcow integration (optional but recommended) ────────────────────────────
# When configured, MailDrop automatically provisions aliases on Mailcow for
# every inbox that's created, and removes them when the inbox is deleted.
# Leave blank to disable; the IMAP catch-all still works without it.
#
# Base URL of your Mailcow instance (no trailing slash).
MAILCOW_URL=https://mail.example.com     # ← CHANGE ME (or leave blank to skip)
# API key: Mailcow → Configuration → Access → API  (read + write key)
MAILCOW_API_KEY=CHANGE_ME_mailcow_api_key
#
# If your Mailcow uses a self-signed TLS certificate uncomment the next line:
# NODE_TLS_REJECT_UNAUTHORIZED=0
`;

// ── Write file ────────────────────────────────────────────────────────────────

fs.writeFileSync(OUT, env, "utf-8");

// ── Summary ───────────────────────────────────────────────────────────────────

console.log("");
console.log(bold(green("✓  .env written successfully!\n")));
console.log(bold("  Auto-generated secrets"));
console.log(`  NEXTAUTH_SECRET  ${cyan(NEXTAUTH_SECRET.slice(0, 12) + "…")}`);
console.log(`  ADMIN_PASSWORD   ${cyan(ADMIN_PASSWORD)}`);
console.log(`  WEBHOOK_SECRET   ${cyan(WEBHOOK_SECRET.slice(0, 16) + "…")}\n`);
console.log(bold("  Next steps — edit .env and set these values:"));
console.log(yellow("  NEXTAUTH_URL") + "       your deployed URL");
console.log(yellow("  MAIL_DOMAIN") + "        e.g.  mail.yourdomain.com");
console.log(yellow("  WEBSITE_URL") + "        same as NEXTAUTH_URL");
console.log(yellow("  DISCORD_BOT_TOKEN") + "  from discord.com/developers");
console.log(yellow("  DISCORD_OWNER_IDS") + "  your Discord user ID");
console.log(yellow("  IMAP_HOST") + "          your Mailcow IMAP host");
console.log(yellow("  IMAP_USER") + "          your catch-all address");
console.log(yellow("  IMAP_PASS") + "          catch-all IMAP password");
console.log(yellow("  MAILCOW_URL") + "        (optional) your Mailcow URL");
console.log(yellow("  MAILCOW_API_KEY") + "    (optional) Mailcow API key\n");
console.log(bold("  To re-generate (overwrites .env):  npm run setup -- --force\n"));
